const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'backend', 'data', 'events.json');
const events = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const missing = [
  {
    id: '550e8400-e29b-41d4-a716-446655440014',
    title_uz: 'Eco Qumita Yig\'ilishi',
    title_ru: 'Заседание Эко-комитета',
    title_en: 'Eco Committee Meeting',
    description_uz: '✅Bugun Tuproqqalʼa tuman ixtisoslashtirilgan maktabida Eco-Schools xalqaro ekologik ta\'lim loyihasi doirasida navbatdagi muhim tadbir tashkil etildi.',
    description_ru: 'Сегодня в специализированной школе Тупроккалинского района прошло очередное важное мероприятие в рамках международного проекта экологического образования Eco-Schools.',
    description_en: 'Today, another important event was organized at the specialized school of Tuproqqala district within the framework of the Eco-Schools international environmental education project.',
    location: 'Main Hall',
    event_date: '2026-01-19',
    event_time: '10:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-01-19T00:00:00.000Z',
    updated_at: '2026-01-19T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440015',
    title_uz: '"ZAKOVAT" intellektual oʻyini',
    title_ru: 'Интеллектуальная игра "Заковат"',
    title_en: '"Zakovat" Intellectual Game',
    description_uz: 'Oʻtkir Hoshimov ijodiga bag\'ishlangan "ZAKOVAT" intellektual o\'yini tashkil etildi.',
    description_ru: 'Организована интеллектуальная игра "Заковат", посвященная творчеству Уткира Хашимова.',
    description_en: 'An intellectual game "Zakovat" dedicated to the work of Utkir Hoshimov was organized.',
    location: 'Main Hall',
    event_date: '2026-01-29',
    event_time: '1:00 PM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-01-29T00:00:00.000Z',
    updated_at: '2026-01-29T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440016',
    title_uz: '"BOʻLAJAK MEDIKLAR" nomli tadbir',
    title_ru: 'Мероприятие "БУДУЩИЕ МЕДИКИ"',
    title_en: 'Event "FUTURE MEDICS"',
    description_uz: '11-"B" sinf oʻquvchilari ishtirokida "BOʻLAJAK MEDIKLAR" nomli tadbir tashkil etildi',
    description_ru: 'С участием учеников 11-"В" класса организовано мероприятие "БУДУЩИЕ МЕДИКИ"',
    description_en: 'Event "FUTURE MEDICS" was organized with the participation of students from class 11-"B"',
    location: 'Main Hall',
    event_date: '2026-01-28',
    event_time: '11:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-01-28T00:00:00.000Z',
    updated_at: '2026-01-28T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440017',
    title_uz: '🕯IKKI BUYUK SIYMO🕯',
    title_ru: '🕯ДВЕ ВЕЛИКИЕ ФИГУРЫ🕯',
    title_en: '🕯TWO GREAT FIGURES🕯',
    description_uz: '🕯Tadbirda Alisher Navoiy va Zahiriddin Muhammad Bobur ijodidan gʻazal va ruboiylar, hikmatli soʻzlar aytildi.',
    description_ru: 'На мероприятии прозвучали газели, рубаи и мудрые слова из творчества Алишера Навои и Захириддина Мухаммада Бабура.',
    description_en: 'Ghazals, rubais, and words of wisdom from the works of Alisher Navoi and Zahiriddin Muhammad Babur were recited at the event.',
    location: 'Main Hall',
    event_date: '2026-02-09',
    event_time: '10:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-02-09T00:00:00.000Z',
    updated_at: '2026-02-09T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440018',
    title_uz: 'Xalqaro ilm fan sohasidagi xotin-qizlar kuni',
    title_ru: 'Международный день женщин и девочек в науке',
    title_en: 'International Day of Women and Girls in Science',
    description_uz: 'Xalqaro ilm fan sohasidagi xotin-qizlar kuni munosabati bilan ma\'naviy-ma\'rifiy tadbir tashkil etildi.',
    description_ru: 'В связи с Международным днем женщин в науке было организовано духовно-просветительское мероприятие.',
    description_en: 'A spiritual and educational event was organized on the occasion of the International Day of Women in Science.',
    location: 'Main Hall',
    event_date: '2026-02-13',
    event_time: '10:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-02-13T00:00:00.000Z',
    updated_at: '2026-02-13T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440019',
    title_uz: 'Zulfiya Isroilova tavallud tadbiri',
    title_ru: 'Мероприятие ко дню рождения Зульфии Исраиловой',
    title_en: 'Zulfiya Israilova\'s Birthday Event',
    description_uz: 'Zulfiya Isroilova tavallud sanasiga bagʻishlangan maʼnaviy-maʼrifiy tadbir boʻlib oʻtdi.',
    description_ru: 'Состоялось духовно-просветительское мероприятие, посвященное дню рождения Зульфии Исраиловой.',
    description_en: 'A spiritual and educational event dedicated to the birthday of Zulfiya Israilova was held.',
    location: 'Main Hall',
    event_date: '2026-02-27',
    event_time: '1:00 PM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-02-27T00:00:00.000Z',
    updated_at: '2026-02-27T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440020',
    title_uz: '“МАСЛЕНИЦА”',
    title_ru: '“МАСЛЕНИЦА”',
    title_en: '“MASLENITSA”',
    description_uz: '“МАСЛЕНИЦА” mavzusida ma\'naviy-ma\'rifiy tadbir tashkil etildi.',
    description_ru: 'Организовано духовно-просветительское мероприятие на тему “МАСЛЕНИЦА”.',
    description_en: 'A spiritual and educational event on the theme of “MASLENITSA” was organized.',
    location: 'Main Hall',
    event_date: '2026-03-05',
    event_time: '10:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-03-05T00:00:00.000Z',
    updated_at: '2026-03-05T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440021',
    title_uz: '8-mart Xalqaro xotin-qizlar kuni',
    title_ru: '8 марта - Международный женский день',
    title_en: 'March 8 - International Women\'s Day',
    description_uz: 'Tuproqqalʼa tuman ixtisoslashtirilgan maktabida "Ayol baxtli bo\'lsa, jamiyat baxtlidir" shiori ostidagi tadbir o\'tkazildi',
    description_ru: 'В специализированной школе Тупроккалинского района прошло мероприятие под девизом "Если женщина счастлива, счастливо и общество"',
    description_en: 'An event under the motto "If a woman is happy, society is happy" was held at the specialized school of Tuproqqala district',
    location: 'Main Hall',
    event_date: '2026-03-06',
    event_time: '1:00 PM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-03-06T00:00:00.000Z',
    updated_at: '2026-03-06T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440022',
    title_uz: '🎓 Osiyo xalqaro universiteti vakillari bilan uchrashuv tashkil etildi.',
    title_ru: '🎓 Организована встреча с представителями Международного Азиатского университета.',
    title_en: '🎓 A meeting with representatives of Asian International University was organized.',
    description_uz: '🎓 Osiyo xalqaro universiteti vakillari bilan uchrashuv tashkil etildi.',
    description_ru: '🎓 Организована встреча с представителями Международного Азиатского университета.',
    description_en: '🎓 A meeting with representatives of Asian International University was organized.',
    location: 'Main Hall',
    event_date: '2026-03-13',
    event_time: '11:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-03-13T00:00:00.000Z',
    updated_at: '2026-03-13T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440023',
    title_uz: '21-mart "Navro\'z" umumxalq bayrami',
    title_ru: '21 марта — всенародный праздник «Навруз»',
    title_en: 'March 21 - "Navruz" national holiday',
    description_uz: '"Navro\'zni ulug\'lash – insonni ulug\'lashdir!" degan bosh g\'oya asosida oʻtkazish maqsadida Tuproqqalʼa tuman ixtisoslashtirilgan maktabida "Navroʻz sayli" boʻlib oʻtdi.',
    description_ru: 'В целях проведения под главной идеей «Прославлять Навруз – прославлять человека!» в специализированной школе Тупроккалинского района прошел «Праздник Навруз».',
    description_en: 'In order to hold it under the main idea "To glorify Navruz is to glorify a person!", a "Navruz festival" was held at the specialized school of Tuproqqala district.',
    location: 'Main Hall',
    event_date: '2026-03-19',
    event_time: '11:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-03-19T00:00:00.000Z',
    updated_at: '2026-03-19T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440024',
    title_uz: '"DIREKTOR STIPENDIYASI" topshirish tadbiri',
    title_ru: 'Церемония вручения "СТИПЕНДИИ ДИРЕКТОРА"',
    title_en: '"PRINCIPAL\'S SCHOLARSHIP" Awarding Event',
    description_uz: 'Kurbanbayev Bunyodbek Jumaboy oʻgʻli 5-"A" sinf oʻquvchisi. Quranboyev Suhrobbek Yunusbek oʻgʻli 5-"A" sinf oʻquvchisi. Xudayberganova Goʻzalxon Oybek qizi 8-"A" sinf o\'quvchisi',
    description_ru: 'Ученик 5-"А" класса Курбанбаев Бунёдбек Жумабой угли. Ученик 5-"А" класса Куранбоев Сухроббек Юнусбек угли. Ученица 8-"А" класса Худайберганова Гюзалхон Ойбек кизи',
    description_en: '5th-"A" grade student Kurbanbayev Bunyodbek Jumaboy ugli. 5th-"A" grade student Quranboyev Suhrobbek Yunusbek ugli. 8th-"A" grade student Khudayberganova Guzalxon Oybek kizi',
    location: 'School Yard',
    event_date: '2026-04-03',
    event_time: '11:00 AM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-04-03T00:00:00.000Z',
    updated_at: '2026-04-03T00:00:00.000Z'
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440025',
    title_uz: 'Amir Temur tavalludining 690 yilligi',
    title_ru: '690-летие со дня рождения Амира Темура',
    title_en: '690th anniversary of the birth of Amir Temur',
    description_uz: 'Sohibqiron Amir Temur hayoti hamda tarixiy merosini keng targ\'ib qilish, o\'quvchilarda vatanparvarlik, tarixiy xotiraga hurmat tuyg\'ularini yanada mustahkamlashdan iborat bo\'ldi',
    description_ru: 'Мероприятие было направлено на широкую популяризацию жизни и исторического наследия Амира Темура, дальнейшее укрепление чувства патриотизма и уважения к исторической памяти у учащихся',
    description_en: 'The event aimed at widely promoting the life and historical legacy of Amir Temur, further strengthening feelings of patriotism and respect for historical memory among students',
    location: 'Main Hall',
    event_date: '2026-04-09',
    event_time: '12:30 PM',
    image_url: null,
    category: 'Cultural',
    published: true,
    created_at: '2026-04-09T00:00:00.000Z',
    updated_at: '2026-04-09T00:00:00.000Z'
  }
];

fs.writeFileSync(filePath, JSON.stringify([...events, ...missing], null, 2));
console.log('Successfully migrated 12 events.');
